version: '3'
services:
  web:
    image: nickreed/rpi-second:latest
    # build: 
    #   context: .
    #   args: 
    #     NODE_ENV: "development"
    environment:
      - BASICS_ZIP_URL=${BASICS_ZIP_URL}
      - PORT=${PORT}
      - MONGODB_CONNECTION=${MONGODB_CONNECTION}
      - MONGODB=${MONGODB}
      - REDIS_HOST=${REDIS_HOST}
      - DEFAULT_PASSPHRASE=${DEFAULT_PASSPHRASE}
      - IPFS_HOST=${IPFS_HOST}
      - IPFS_PORT=${IPFS_PORT}
      - IPFS_PROTOCOL=${IPFS_PROTOCOL}
      - APP_OPEN_GRAPHQL=${APP_OPEN_GRAPHQL}
      - RPI_HOST_AND_PORT=${RPI_HOST_AND_PORT}
      - DEFAULT_LAUNCH_PLATFORM=${DEFAULT_LAUNCH_PLATFORM}
      - DEFAULT_LAUNCH_APPID=${DEFAULT_LAUNCH_APPID}
      - STELLAR_NETWORK=${STELLAR_NETWORK}
      # used by /wait (not working) - WAIT_HOSTS=127.0.0.1:27017
      # used by /wait (not working) - WAIT_HOSTS_TIMEOUT=60
    network_mode: host
    expose:
      - 7001
    ports:
      - "7001:7001"
    # links:
    #   - redis
    #   - mongodb
    depends_on:
      - redis
      - mongodb
      # - ipfs
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyAMA0:/dev/ttyAMA0
      - /dev/snd:/dev/snd
    volumes:
      - /boot:/boot
      - /usr/share/sounds/alsa/:/usr/share/sounds/alsa/
    privileged: true
    command: >
      /bin/bash -c "
        while ! nc -z 127.0.0.1 27017;
        do
          echo sleeping;
          sleep 10;
        done;
        echo Connected to 127.0.0.1:27017;
        sleep 10;
        npm run pi;
      "
    # command: ["/usr/src/app/wait-for-it.sh", "127.0.0.1:27017", "--", "npm", "run", "pi"]
    # /usr/src/app/wait-for-it.sh

  redis:
    image: hypriot/rpi-redis
    ports:
      - "6379:6379"

  mongodb:
    image: ftavares/rpi-mongo:3.0.9
    ports:
      - "27017:27017"
    command: ["mongod", "--journal", "--rest"]
    # not sure if the following works, cuz VOLUME is not specified in Dockerfile for ftavares/rpi-mongo:3.0.9
    volumes:
      - mongodb-data:/data/db

  # ipfs:
  #   # image: ipfs/go-ipfs
  #   image: jkms/rpi-go-ipfs
  #   # container_name: "ipfs"
  #   # restart: always
  #   expose: # internal links
  #     - 4001
  #     - 5001
  #     - 8080
  #   ports: # externally available
  #     - 4001:4001
  #     - 5001:5001
  #     - 8080:8080 
  #   volumes:
  #     - ipfs-data:/data

  # start_dependencies:
  #   image: dadarek/wait-for-dependencies
  #   depends_on:
  #     - mongodb
  #   command: 127.0.0.1:27017


volumes:
  mongodb-data:
  ipfs-data:



#   web:
#     build: 
#       context: .
#       args: 
#         NODE_ENV: "development"
#     environment:
#       - MONGODB
#       - PORT_ON
#       - LANGUAGE_SERVER
#       - BASICS_ZIP_URL
#       - DEFAULT_PASSPHRASE
#       - WAIT_HOSTS=mongodb:27017
#     # image: nickreed/rpi-second:latest
#     # volumes:
#     #   - .:/usr/src/app
#     privileged: true
#     network_mode: host
#     ports:
#       - "7001:7001"
#     # links:
#     #   - redis
#     #   - mongodb
#     depends_on:
#       - redis
#       - mongodb
#       - ipfs
#     devices:
#       - "/dev/ttyUSB0:/dev/ttyUSB0"
#       - "/dev/ttyAMA0:/dev/ttyAMA0"
#     volumes:
#       - /boot:/boot

#   # ngrok:
#   #   build: https://github.com/nicholasareed/docker-rpi-ngrok.git
#   #   environment:
#   #     - NGROK_AUTH=${NGROK_AUTH}
#   #     - "NGROK_PORT=${COMPOSE_PROJECT_NAME}_web_1:7001"
#   #     - NGROK_SUBDOMAIN=${PUBLIC_SUBDOMAIN}
#   #   links:
#   #     - web:app

#   #   # ports:
#   #   #   - "4040:4040"
