#cloud-config
# vim: syntax=yaml
#

# The current version of cloud-init in the Hypriot rpi-64 is 0.7.9
# When dealing with cloud-init, it is SUPER important to know the version
# I have wasted many hours creating servers to find out the module I was trying to use wasn't in the cloud-init version I had
# Documentation: http://cloudinit.readthedocs.io/en/0.7.9/index.html

# Set your hostname here, the manage_etc_hosts will update the hosts file entries as well
hostname: pi3second
manage_etc_hosts: true

# You could modify this for your own user information
users:
  - name: pirate
    gecos: "Hypriot Pirate"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video,input
    plain_text_passwd: hypriot
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }

# # Set the locale of the system
locale: "en_US.UTF-8"

# # Set the timezone
# # Value of 'timezone' must exist in /usr/share/zoneinfo
# timezone: "America/Los_Angeles"

# # Update apt packages on first boot
# package_update: true
# package_upgrade: true
# package_reboot_if_required: true
package_upgrade: false

# # Install any additional apt packages you need here
# packages:
#  - ntp

# # WiFi connect to HotSpot
# you also have to set "enable_uart=0" in config.txt
#
# # - use `wpa_passphrase SSID PASSWORD` to encrypt the psk
write_files:
  # Second boot file (base64) 
  # - base64 boot.sh
  - encoding: b64
    content: IyEvdXNyL2Jpbi9lbnYgYmFzaAoKIyBSdW5zIG9uIFJQaSBib290IAojIC0gY2hlY2tzIGZvciAiV2lmaSBBUCBNb2RlIiAKIyAtIHJ1bnMgaW5zdGFsbC5zaCBpZiBub3QgeWV0IGluc3RhbGxlZCAoYW5kIGNvbm5lY3RlZCkgCgo=
    path: /home/pirate/boot.sh

  ## Wifi Setup 
  - content: |
      allow-hotplug wlan0
      iface wlan0 inet dhcp
      wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
      iface default inet dhcp
    path: /etc/network/interfaces.d/wlan0
  - content: |
      country=YourContryCode
      ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
      update_config=1
      network={
      ssid=""
      psk=""
      proto=RSN
      key_mgmt=WPA-PSK
      pairwise=CCMP
      auth_alg=OPEN
      }
    path: /etc/wpa_supplicant/wpa_supplicant.conf

  ## USB Audio and usb capture device 
  # - should get updated on boot with ACTUAL hardware/card info (0/1) 
  - content: |
      pcm.!default {
        type asym
        capture.pcm "usbmic"
        playback.pcm "usbspeaker"
      }
      pcm.usbmic {
        type plug
        slave {
          pcm "hw:2,0"
        }
      }
      pcm.onboardspeaker {
        type hw
        card 0
      }
      pcm.usbspeaker {
        type hw
        card 1
      }
      ctl.!default {
       type hw card 0
      }
    path: /etc/asound.conf


# These commands will be ran once on first boot only
runcmd:
  # Pickup the hostname changes
  - 'systemctl restart avahi-daemon'

  # Activate WiFi interface
  - 'ifup wlan0'

  # Boot.sh for second
  - 'bash /home/pirate/boot.sh'
